# fly.toml app configuration file generated for jaam on 2023-06-09T11:15:38-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jaam"
primary_region = "dfw"

[deploy]
  release_command = "npm run seed"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
