export { default as Header } from './Header';
export { default as Home } from './Home';
export { default as Products } from './Products';
export { default as About } from './About';
export { default as Cart } from './Cart';
export { default as Checkout } from './Checkout';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Logout } from './Logout';
export { default as CategoryDetails } from './CategoryDetails';
export { default as ProductDetails } from './ProductDetails';
export { default as SingleProductView } from './SingleProductView';
export { default as ContactUs } from './ContactUs';
export { default as Footer } from './Footer';
export { default as ProfilePage } from './ProfilePage';
export { default as CartWithAccountView } from './CartWithAccountView';
export {default as CategoryView } from './CategoryView';
