const Images = {
    HomeBanner: require('./HomeBanner.jpg'),
    CategoryOverEar: require('./Category-OverEar.jpg'),
    CategorySpeaker: require('./Category-Speaker.jpg'),
    CategoryAccessories: require('./Category-Accessories.jpg'),
    2: require('./InEarHeadPhoneBlack.jpg'),
    3: require('./OverEarHeadphoneWhite.jpg'),
    1: require('./SpeakerBlack.jpg'),
    4: require('./pexels-garrett-morrow-1649771.jpg'),
    5: require('./pexels-jens-mahnke-844923.jpg'),
    6: require('./pexels-nao-triponez-128611.jpg'),
    7: require('./pexels-tom-swinnen-1034653.jpg'),
    8: require('./SpeakerBlack.jpg'),
    9: require('./InEarHeadPhoneBlack.jpg'),
    10: require('./OverEarHeadphoneWhite.jpg'),
    11: require('./pexels-garrett-morrow-1649771.jpg'),
    12: require('./pexels-jens-mahnke-844923.jpg'),
    13: require('./pexels-nao-triponez-128611.jpg'),
    14: require('./pexels-tom-swinnen-1034653.jpg'),
    15: require('./SpeakerBlack.jpg'),
    16: require('./InEarHeadPhoneBlack.jpg'),
    17: require('./pexels-pixabay-159472.jpg'),
    HeadphoneCase: require('./HeadphoneCase.jpg'),
    JAAMLOGO: require('./JAAMLogo.png'),
    18: require('./speaker-4397893_1280.png'),
};

export default Images;